name: Lint with Ruff

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      
      # Install uv
      - name: Install uv
        run: curl -LsSf https://astral.sh/uv/install.sh | sh

      # Install and run Ruff
      - name: Run Ruff
        run: |
          uv pip install ruff
          uv run ruff check .
          uv run ruff format --check . 